### ISSUE TITLE
Please consider allowing alpha numeric Record IDs to use Custom List

### ISSUE THREAD

**Issue by jhoitenga** [susom/mass-delete#15]
This is similar to the issue Luke reported where the module does not allow you to use non-numeric Record IDs however I wanted to open a separate issue so that alpha numeric Record IDs could also be considered. Example: XX-8675309

**Comment by yasukawa** [comment]
v1.1.7 was just submitted to the consortium which will allow non-numeric record IDs in the Custom List and will validate that records entered in the list exist in the project.  Please download the new version once approved by the consortium.
