### ISSUE TITLE
Server Time Out when too many records

### ISSUE THREAD

**Issue by tertek** [susom/mass-delete#3]
As stated in #2 the module becomes unusable if there are too many records. It does not make sense to build all checkboxes at once, as the code does in line 114. It would make more sense to load chunks asynchronously and setup a tiny delete request handled by Javascript on the client-side.

**Comment by 123andy** [comment]
Hey @tertek  - I agree...  I just had that 'select' code left over from a previous plugin years ago and copied it for a project...  I haven't had time to invest much but it could certainly be improved.  Further, it could use the record list tables too now that they exist...  Open to pull requests as I'm probably not going to have time to do this myself.

**Comment by tertek** [comment]
Opened a PR https://github.com/susom/mass-delete/pull/4

**Comment by 123andy** [comment]
Approved!

**Comment by mschulze0** [comment]
Wow, great job @tertek thanks!
