### ISSUE TITLE
Integration with Reports

### ISSUE THREAD

**Issue by 123andy** [susom/mass-delete#5]
@tertek - since you're on a roll:

Two ideas for mass_delete:

1) Ability to select record_ids from an existing report.  So, you could craft a report with all your 'do not want' data and then just from the dropdown in mass_delete, pick the report and it would extract all of the record_ids and pre-populate them in the record selection box.

2) As an added bonus - the ability to then place this on a cron.  So, you could have a daily cron that would delete all the records that match a query defined in a report.  In the report you might use some datediff logic or if a bunch of fields are empty, etc..   In the case of a public survey, you could put a timestamp field on the survey and then make sure the survey is more than a day old but is not complete - in that case, delete it.

**Comment by tertek** [comment]
@123andy thank you for the ideas. Sounds legit. 
I will check with my team and see if I can roll on with this :)

**Comment by tertek** [comment]
Unfortunately, I could not find resources to look on this. Maybe we should add a Roadmap to the README and someone else could take it over? Then this issue could be closed as well.
